import logging
import requests
from django.conf import settings
import time
from openai import OpenAI
import os
logger = logging.getLogger(__name__)

class AIServiceError(Exception):
    """Raised when communication with Ollama fails."""
    pass
class AIService:
    @staticmethod
    def generate_explanation(prompt:str)->str:
        
        """

        Send the prompt to Ollama and return the generated text.
        Args:
       prompt: Prompt generated by Prompt Builder.
        Returns:
         AI response as plain text.
        """
        url = f"{settings.OLLAMA_BASE_URL}/api/generate"
        try:
            print("\n" + "=" * 60)
            print("PROMPT SENT TO OLLAMA")
            print("=" * 60)
            print(prompt)
            print("=" * 60)
            print("Prompt Length:", len(prompt))
            payload={
              "model": settings.OLLAMA_MODEL,
              "prompt":prompt,
              "stream":False,
              
             }
            start = time.time()
            response=requests.post(url,json=payload,timeout=settings.OLLAMA_TIMEOUT)
            response.raise_for_status()
            end = time.time()

            print("=" * 60)
            print("OLLAMA RESPONSE TIME")
            print(end - start)
            print("=" * 60)
            data=response.json()
            ai_response=data.get("response")
            if not ai_response:
                raise ValueError("AI response is empty")
            return ai_response
        except requests.RequestException as e:
            print("========== OLLAMA ERROR ==========")
            print(e)
            print("==================================")

            logger.exception("Error while calling AI service: %s", e)

            raise AIServiceError(
            f"Failed to communicate with Ollama: {e}"
           ) from e
        except ValueError as e:
            logger.exception("Invalid AI response.")
            raise AIServiceError("Invalid AI response.") from e

    @staticmethod
    def generate_explanation_groq(prompt:str)->str:
        """semd prompt to groq"""
        client=OpenAI(
            api_key=settings.GROQ_API_KEY,
            base_url="https://api.groq.com/openai/v1"
        )
        try:
            logger.info("Sending explanation request to Groq")
            start = time.time()
            response=client.chat.completions.create(
                messages=[  {
                    "role": "system",
                    "content": "You are a helpful AI assistant."
                },
                    {"role": "user", "content": prompt}
                ],
                model="openai/gpt-oss-20b"
            )
            
            end = time.time()
            logger.info("Groq explanation response received in %.2fs", end - start)
            ai_response=response.choices[0].message.content
            
            if not ai_response:
                raise ValueError("AI response is empty")
            return ai_response
        except Exception as e:
            logger.exception("Error while calling AI service: %s", e)
            raise AIServiceError("Failed to communicate with GROQ.") from e
       
    @staticmethod
    def chat_with_tools_groq(messages: list) -> dict:
        """
        Send a multi-turn conversation to Groq with tool/function calling enabled.

        HOW TOOL CALLING WORKS (step by step):
        1. We send the full conversation history as a list of {"role": ..., "content": ...} dicts.
        2. We also pass a `tools` list -- the TRIAGE_TOOLS schema defined in ai_tools.py.
        3. We set tool_choice="auto" which means: the model decides when to call a tool vs reply.
        4. Groq processes the conversation and returns ONE of two things:
           a) A normal assistant message -- response.choices[0].message.content is set
           b) A tool call -- response.choices[0].message.tool_calls is set (content is empty)
        5. We inspect which one we got and return a typed dict so the view can branch cleanly.

        Args:
            messages: Full conversation history including the system prompt as the first item.
                      Format: [{"role": "system", "content": "..."}, {"role": "user", ...}, ...]

        Returns:
            {"type": "message",   "content": str}         -- AI replied with plain text
            {"type": "tool_call", "name": str, "arguments": dict} -- AI called a function
        """
        # Import here to avoid circular imports (ai_tools imports nothing from ai_service)
        from .ai_tools import TRIAGE_TOOLS
        import json as _json

        client = OpenAI(
            api_key=settings.GROQ_API_KEY,
            base_url="https://api.groq.com/openai/v1",
        )

        try:
            logger.info("Sending chat with tools request to Groq (Message count: %d)", len(messages))
            start = time.time()
            response = client.chat.completions.create(
                # Model configured in settings (defaults to openai/gpt-oss-20b on Groq)
                model=settings.GROQ_CHAT_MODEL,
                messages=messages,
                # tools: the list of function schemas the AI is allowed to call.
                tools=TRIAGE_TOOLS,
                # tool_choice="auto": let the model decide when it has enough info to call
                # the tool vs. when it should keep asking follow-up questions.
                tool_choice="auto",
            )
            end = time.time()
            logger.info("Groq tool response received in %.2fs", end - start)

            message = response.choices[0].message

            # --- CASE A: The model called a tool ---
            if message.tool_calls:
                tool_call = message.tool_calls[0]
                name = tool_call.function.name
                arguments = _json.loads(tool_call.function.arguments)
                logger.info("Groq tool triggered: %s", name)
                return {"type": "tool_call", "name": name, "arguments": arguments}

            # --- CASE B: The model replied with a regular text message ---
            content = message.content
            if not content:
                raise ValueError("AI returned an empty message and no tool call.")
            return {"type": "message", "content": content}

        except Exception as e:
            logger.exception("Error while calling Groq with tools")
            raise AIServiceError("Failed to communicate with Groq (tool calling).") from e