# Generated by Django 6.0.2 on 2026-02-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], default='pending', max_length=20),
        ),
    ]
