# Generated by Django 6.0.2 on 2026-03-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_case_assigned_doctor_case_assigned_nurse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
