# Generated by Django 6.0.2 on 2026-04-03 16:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0005_case_diagnosis_case_prescription_alter_case_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='registration_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
