# Generated by Django 6.0.2 on 2026-07-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_case_registration_notes_case_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ai_explanation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
