# Generated by Django 6.0.2 on 2026-09-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0007_case_ai_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='ai_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
